[package]
name = "assignment-02"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44.2", features = ["full"] }
tree-sitter = "0.25.3"
tree-sitter-java = "0.23.5"
once_cell = "1.21.3"